### PR TITLE
Add parcel-plugin-mdx

### LINKED ISSUE #54: Implement parcel bundler plugin

### PR DESCRIPTION
**Pull request by ifyoumakeit**
- Add parcel-plugin-mdx commits from @hamlim
- Move plugin example to examples folder
- Add test for plugin for components and Markdown
- Match package structure of monorepo
- Move tag/react to peerDependencies

closes #54

### CODE REVIEW

**Comment by ifyoumakeit** [comment]
The Parcel example won't work due to the package not being published. This could be fixed by adding `examples/*` to `lerna.json` so everything can be in sync locally. yarn workspaces could also help here. 

Until it is published you need to...

```bash
cd packages/parcel-plugin-mdx
yarn link
cd ../../examples/parcel
# Remove `"@mdx-js/parcel-plugin-mdx": "0.13.1-1"` from`package.json`
yarn
# Add back `"@mdx-js/parcel-plugin-mdx": "0.13.1-1"` to `package.json`
yarn link @mdx-js/parcel-plugin-mdx
```

The example also needs to be updated afterwards to use the new version.

**Comment by ifyoumakeit** [comment]
Pushed a fix to link `tag` and `parcel-plugin-mdx` through relative file links in `example-parcel`. You may need to remove node_modules (if there already) in the examples/parcel folder before re-installing.

**Comment by ifyoumakeit** [comment]
@johno, anything else you'd like to see?

**Comment by johno** [comment]
This is looking great, thanks!

Can you please nuke the yarn-error file (feel free to add to gitignore too)? Aside from that, lgtm 👌

**Comment by ifyoumakeit** [comment]
All good, added a general ignore for `*-error.log`

**Comment by johno** [comment]
Thanks!

**Pull request merged**
