### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by Boro23-wq**
Update on the MDX doc.

### CODE REVIEW

**Comment by wooorm** [comment]
@Boro23-wq Why should this be accepted? This looks like a bunch of meaningless changes…

**Comment by Boro23-wq** [comment]
@wooorm Certainly not how I see it. Definitely a non-essential change but the doc doesn't sound hasty anymore.

**Comment by ChristianMurphy** [comment]
Welcome @Boro23-wq!
The readme is to some degree intentionally concise, too much information and too much elaboration can make getting started more difficult.
Sometimes "hasty" isn't a necessarily bad thing :slightly_smiling_face: 
There are a few items tagged good first issue, which may be a good starting point for contributing https://github.com/mdx-js/mdx/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue+%F0%9F%91%8B%22

**Comment by JounQin** [comment]
close due to inactive.

Should we try something like https://github.com/actions/stale.

**Pull request closed without merging**
