### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by mvasilkov**
Under "Use MDX for .md files", the regex should match both .md and .mdx

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]
thanks @mvasilkov!

**Comment by wooorm** [comment]
Why should that be the case?

The question mark used to be there, and was removed here: https://github.com/mdx-js/mdx/commit/6f3dc9cb359fdb1ae29fb4cc898583f6b8e3b8b6. The reason behind it is that `.mdx` and `.md` are not the same. I think it’s a good default to only support `.mdx` by default. If you want `.md` file too, you are of course free to do so.

**Comment by ChristianMurphy** [comment]
The section this titled

```markdown
### Use MDX for `.md` files

The Next.js MDX plugin allows for you to also use MDX parsing for `.md` files:
```

this PR updates the example to match the section description.
It could be that this section should be removed entirely as an alternative.
Thoughts? :thought_balloon:

**Review by wooorm — COMMENTED** [review]
disregard my previous comment, nice catch!

**Pull request merged**
