### PR TITLE
Adds ability to use gifs with remark-images.

### PR DESCRIPTION
**Pull request by manovotny**
Can't live without the most popular internet image file type.

### CODE REVIEW

**Comment by johno** [comment]
Looks like the last PR caused a merge conflict, do you mind fixing when you get a chance? Thanks!

**Comment by manovotny** [comment]
You bet! I suspected that would happen.

**Comment by manovotny** [comment]
@johno conflicts resolved!

**Comment by johno** [comment]
Thanks!

**Pull request merged**
