### PR TITLE
Remove large (+20kb) 'change-case' dependency

### LINKED ISSUE #623: The 'change-case' package is bloating bundle size
The [`change-case`](https://www.npmjs.com/package/change-case) dependency is `>20kb` which is pushing us over our bundle size budget. Can it be replaced/inlined?

### PR DESCRIPTION
**Pull request by wilsonpage**
Fixes #623

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@wilsonpage would focusing the npm package to https://github.com/blakeembrey/param-case reduce the bundle size, and keep the edge case handling?

**Comment by johno** [comment]
@ChristianMurphy at this point we _shouldn't_ need any edge case handling since we're only [transforming two known cases](https://github.com/mdx-js/mdx/blob/3686c8dee70addecfb9730726f42e6ce20a5ce35/packages/mdx/mdx-hast-to-jsx.js#L88-L98).

**Comment by timneutkens** [comment]
Updated the pr description to auto-close the issue.

**Comment by wilsonpage** [comment]
@ChristianMurphy `param-case` still depends on the large dependency `no-case`.

**Comment by wilsonpage** [comment]
Updated the PR to cope with the `data123` case.

**Comment by wilsonpage** [comment]
@ChristianMurphy I'm afraid I don't have enough context on this project to write a test. Would take me a while to grok, which I can't afford right now :( Would be great if one of you lot could add one!

**Comment by johno** [comment]
I'll add a few tests in a follow up PR, thanks for the contribution @wilsonpage!

**Pull request merged**
