### PR TITLE
Expose es tokenizer, use lib

### PR DESCRIPTION
**Pull request by johno**

### CODE REVIEW

**Comment by johno** [comment]
Great question: Partially cosmetic and partially because we'd like to expose the MDXAST more easily for folks to use downstream (right now `prettier` is duplicating the logic).

**Comment by johno** [comment]
Going to reopen as a new PR later (post eslint).

**Comment by jonsherrard** [comment]
Hi @johno, what does (post eslint) mean? Is there anything I could help with? I've been messing around with trying to expose the MDXAST myself in light of @mdx-js/mdxast being deprecated.

**Comment by wooorm** [comment]
@jonsherrard I did some work on a replacement with remark-mdx (private, but in this repo). It’s a different (non-existent) issue, and first discussed [here](https://github.com/mdx-js/mdx/pull/314#issuecomment-439643893).

**Comment by jonsherrard** [comment]
I see,

I've ended up writing my own MDXAST generator, based on the spec in the docs and using Acorn, the parser that powers babel, and the `esSyntax` plugin from the deprecated `mdxast`

```js
const mdxAst = treeMap(newTree, node => {
      try {
        // Parse each node with Acorn JSX parser (powers Babel)
        const jsxCheck = jsxParser.parse(node.value, { sourceType: "module" });
        if (jsxCheck.body[0].type === "ImportDeclaration") {
          return Object.assign({}, node, { type: "import" });
        }
        if (jsxCheck.body[0].type === "ExportDeclaration") {
          return Object.assign({}, node, { type: "export" });
        }
        if (
          jsxCheck.type === "Program" &&
          jsxCheck.body[0].type === "ExpressionStatement" &&
          jsxCheck.body[0].expression.type === "JSXElement"
        ) {
          return Object.assign({}, node, { type: "jsx" });
        }
      } catch (e) {
        // Ignore nodes that are not parseable as JSX, remark handles the rest.
      }

      return node;
    });
    return mdxAst;
```

Not sure if it's useful to the main project at all?

Thanks for all your work on MDX - I love it!

**Pull request closed without merging**
