### PR TITLE
Issue 720 Extract babel plugin imports and exports from mdx-remark

### PR DESCRIPTION
**Pull request by Luiginator**
This PR implements https://github.com/mdx-js/mdx/issues/720

Todo:

- [x] Extract plugin
- [x] adjust readme.md of new package
- [x] refactor

### CODE REVIEW

**Comment by JounQin** [comment]
@Luiginator Can you rebase? And @johno please help to review.

**Comment by johno** [comment]
Thanks for your patience! This looks good to go on my end @Luiginator, we just need a rebase and then I can merge.

**Comment by wooorm** [comment]
@Luiginator Friendly ping! 🛎😊

**Comment by wooorm** [comment]
This has landed on `main`. Thanks for your work though @Luiginator!

**Pull request closed without merging**
