### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Ok so there is a Node.js 10 issue. This is why we have to add Node.js 10 to the build matrix to catch these. I'll check the failing build and provide a solution.

**Comment by DanielRuf** [comment]
So please do not yet merge.

**Comment by DanielRuf** [comment]
Should be fine now.

**Comment by timneutkens** [comment]
Cool!

**Comment by johno** [comment]
Thanks!

**Pull request merged**
