### PR TITLE
Issue 550: fix remark-mdx babel plugin resolution

### LINKED ISSUE #550: Babel plugins resolution in remark-mdx
#### Babel plugins resolution in remark-mdx
`remark-mdx` currently specifies a string name in plugin configs:

https://github.com/mdx-js/mdx/blob/b8aa6cc1804af2f52b63fef4897afe4fdf8e1099/packages/remark-mdx/extract-imports-and-exports.js#L50-L51

This is causing issues when mdx-js/mdx (which depends on `remark-mdx`) is used in an environment like vscode extension. I encountered this issue when trying to upgrade mdx for [vscode-mdx-preview](https://github.com/xyc/vscode-mdx-preview) to v1.

This could be resolved by changing the plugin config to
```
babel.createConfigItem([require.resolve('@babel/plugin-syntax-jsx')], { type: 'plugin '}),
babel.createConfigItem([require.resolve('@babel/plugin-proposal-object-rest-spread')], { type: 'plugin'}),
```

### Your environment
VS Code extension that depends on mdx v1.

### Steps to reproduce

Using `mdx-js/mdx` module to compile

### Expected behaviour

mdx-js/mdx works fine

### Actual behaviour

throwing plugin resolution error

### PR DESCRIPTION
**Pull request by xyc**
Closes #550

### CODE REVIEW

**Comment by xyc** [comment]
@wooorm Great questions! Yeah it looks that `createConfigItem` allows babel to cache the config items. I've updated the PR.

**Comment by wooorm** [comment]
Interesting! Well thanks for figuring it out!

Seems that now is failing:

```
  1 | function webpackEmptyContext(req) {
> 2 | 	var e = new Error("Cannot find module '" + req + "'");
    | ^
  3 | 	e.code = 'MODULE_NOT_FOUND';
  4 | 	throw e;
  5 | }


  WebpackError: Cannot find module '/tmp/2b98d254/node_modules/@babel/plugin-syn  tax-jsx/lib/index.js'
```

...but that seems weird to me because it previously worked 🤔

**Comment by xyc** [comment]
🤔yeah it's weird that it didn't work with `now-build`. It was working for my use case and the tests pass though.
I changed it to require plugin directly, similar to #552.

**Comment by johno** [comment]
Thanks @xyc!

**Pull request merged**
