### PR TITLE
docs: add next-mdx to projects

### PR DESCRIPTION
**Pull request by arshad**
Adds `next-mdx` to projects page:

- https://github.com/arshad/next-mdx
- https://next-mdx.org

Thank you

### CODE REVIEW

**Comment by JounQin** [comment]
> @arshad is attempting to deploy a commit to the **MDX** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=MDX&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22ec910d2f72b03f2809fe5268e367a15e285ebd51%22%7D%2C%22id%22%3A%22QmVnUisBLrdVN74rk3vREoLZS8cWwPARnPLDSBnXWYn4ph%22%2C%22org%22%3A%22mdx-js%22%2C%22prId%22%3A1515%2C%22repo%22%3A%22mdx%22%7D).

@johno @wooorm

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
@JounQin What is the question? Are you asking me to allow this? Which site will it be published to?

**Comment by JounQin** [comment]
It should be allowed to build a demo website via vercel automatically, I don't understand why it needs authorization now.

**Comment by wooorm** [comment]
@JounQin I believe [you set this up](https://github.com/mdx-js/mdx/blob/5169bf1f5d7b730b6f20a5eecee0b9ea0d977e56/vercel.json#L4) to deploy the actual site. Not a demo site

**Comment by JounQin** [comment]
> @JounQin I believe [you set this up](https://github.com/mdx-js/mdx/blob/5169bf1f5d7b730b6f20a5eecee0b9ea0d977e56/vercel.json#L4) to deploy the actual site. Not a demo site

That should only affect production deployment from default (main) branch.

https://vercel.com/docs/platform/deployments?query=preview#preview

**Comment by JounQin** [comment]
@wooorm Take https://github.com/mdx-js/mdx/pull/1514#issuecomment-813838975 as example.

**Comment by wooorm** [comment]
OK. Not sure what changed because it used to work fine.
I’m not allowed to change it though.

**Comment by JounQin** [comment]
@johno Do you have any idea? Or do you know who have the permission of vercel MDX team?

**Comment by johno** [comment]
Not sure why it's not configured to deploy forks/branches. Just approved this PR, hopefully it persists for other branches otherwise we'll need to look into that.

**Pull request merged**
