### PR TITLE
feat: Add `babel-plugin-remove-export-keywords`

### PR DESCRIPTION
**Pull request by johnletey**
@johno Here you go!

Closes GH-698

### CODE REVIEW

**Comment by johno** [comment]
Thanks a ton! 😻 😻😻

Do you mind maybe bringing over the test and setting up the `package.json` to mirror the others in this project? 🙏

**Comment by johnletey** [comment]
Sorry that took so long @johno ... but I have added the test (which doesn't pass because new-lines are added when it formats, but I didn't want to change anything before running it by you) and also have formatted the `package.json` like the rest of the packages

**Comment by johno** [comment]
Amazing! Feel free to change the fixture so that it passes 👍

**Comment by johnletey** [comment]
Will do!

**Pull request merged**
