### PR TITLE
Update site dependencies

### PR DESCRIPTION
**Pull request by ChristianMurphy**
This updates the playground, give it a try in the Vercel preview below.

resolves #2061 
resolves #2060

### CODE REVIEW

**Comment by wooorm** [comment]
Looks like syntax highlighting doesn’t work: https://mdx-git-fork-christianmurphy-codemirror-6-mdx.vercel.app/playground/ anymore. I see some errors in the console from codemirror too

**Comment by ChristianMurphy** [comment]
Thanks!
Took a bit to track that down.
Turns out the package lock file needs to be explicitly deduplicated when updating codemirror to ensure all the packages land on compatible versions.

**Comment by ChristianMurphy** [comment]
Well, good news it fixed the site. 🎉 
Bad news, it turned up a conflict between https://github.com/syntax-tree/estree-util-to-js/releases/tag/1.1.1 and `vFile`
and some changes to uvu and esbuild which appear to break us 😅

**Comment by ChristianMurphy** [comment]
With a bit of lockfile surgery both the side and tests look happy.
Instead of a general `npm upgrade`, it uses `npm update {individual codemirror package names}` followed by `npm dedupe`.

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thank you!

**Pull request merged**
