### PR TITLE
Update foot-site.jsx

### PR DESCRIPTION
**Pull request by git-create-devben**
Make a small changes I change Twitter to X in a professional way 

Example of the code:

X (formerly Twitter)

### CODE REVIEW

**Comment by wooorm** [comment]
Meh, I don’t really see it. I feel like everyone knows the term twitter

**Comment by git-create-devben** [comment]
> Meh, I don’t really see it. I feel like everyone knows the term twitter

You're right, sigh I don't really know how to defend it but  I just feel like Is a good little changes lol 😂 but trust me most websites are now using X or X(formerly Twitter)  

this is the code:
image

**Comment by remcohaszing** [comment]
The (partial) Twitter → X rebrand is so stupid. I’m still waiting for the day they announce this was a joke and revert the whole thing.

I just checked some miscellaneous other sites. Some call it _X_. Some call it _Twitter_. Some call it _X (formerly Twitter)_. Some use the bird icon. Some use the X icon.

I have no strong feelings what to do here, but I lean towards keeping _Twitter_.

**Comment by wooorm** [comment]
Yeah I’m just going to go with: Elon is at best annoying at worst willfully purposefully destroying twitter, so I’m using that name for a while more.

Thanks for wanting to contribute tho!

**Pull request closed without merging**
