### PR TITLE
Add types to `@mdx-js/preact`

### PR DESCRIPTION
**Pull request by ChristianMurphy**
mostly the same as mdx react typing https://github.com/mdx-js/mdx/blob/9a33ae598b9f84afa4f95e71f605a08c081e96bb/packages/react/types/index.d.ts
except:
* disable the `disableParentContext` property that mdx react has (not sure if it is supported in preact)
* adding configuration for `jsxFactory` so TypeScript looks at preact's `h` function for JSX scripting.

### CODE REVIEW

**Comment by wooorm** [comment]
Thoughts on who could help review whether this is good? Can we reach out to the folks that contributed the mdx/preact?

**Comment by ChristianMurphy** [comment]
> Can we reach out to the folks that contributed the mdx/preact?

Sounds like a plan

/cc @ChristopherBiscardi who contributed https://github.com/mdx-js/mdx/pull/955 to mdx preact
/cc @JounQin who contributed https://github.com/mdx-js/mdx/pull/1023 to mdx preact

**Comment by ChristopherBiscardi** [comment]
looks fine to me as long as it works with the new build stuff we're implementing (microbundle basically, which it does)

**Review by ChristopherBiscardi — APPROVED** [review]

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Looks good to go, but there are conflicts

**Comment by johno** [comment]
Thanks!

**Pull request merged**
