### PR TITLE
Run tag build in bootstrap command

### LINKED ISSUE #377: Fresh repository clone won't test without extra build step
### Subject of the issue

When doing a fresh clone of the `mdx` repository the `test` and `format` instructions fail due to `/packages/tag` not being built.

I do not know if this is specifically related to a `Windows` development environment. I discussed this with @silvenon and initially we suspected this was related to it being on Windows but the fact that it is related to `tag` not being built makes me question that.

### Your environment

*   Windows 10
*   MDX latest code
*   Node 8.11.2, Yarn 1.12.0

### Steps to reproduce

Clone a completely clean instance of the repository. Run `yarn` followed by `yarn bootstrap` followed by `yarn test`.

### Expected behaviour

The tests should run.

### Actual behaviour

The tests fail with message that `@mdx-js/tag` cannot be found.

### Hotfix

Go to `/packages/tag` directory and run `yarn build`. After that the tests run and passes.

### PR DESCRIPTION
**Pull request by mxstbr**
Closes #377

### CODE REVIEW

**Comment by mxstbr** [comment]
Does that run on bootstrap?

**Comment by timneutkens** [comment]
@mxstbr it runs once you run `yarn` / `npm install` because of the way installing runs prepublish after installing modules.

**Comment by timneutkens** [comment]
cc @johno

**Comment by johno** [comment]
Thanks!

**Pull request merged**
