### PR TITLE
Retry: Automate canary releases

### PR DESCRIPTION
**Pull request by leimonio**

### CODE REVIEW

**Comment by leimonio** [comment]
@timneutkens @wooorm it seems like we're missing some configuration here. Is this the first try for automated releases to npm https://travis-ci.org/mdx-js/mdx/jobs/482421219#L592

**Comment by wooorm** [comment]
Hmm, I have no experience with this, so I don’t know. But @johno’s been working on this!

**Comment by johno** [comment]
Ah, yeah I'm assuming we haven't set up an npm token yet on Travis (I know I haven't yet), I can do so this evening. Thank you for implementing this @leimonio!

**Comment by leimonio** [comment]
@johno is this something that has to be enabled on the npm account? Thanks for taking care of it! We can then rerun the worklfow, and check if deploy gets completed.

**Pull request merged**
