### PR TITLE
chore: yarn upgrade

### PR DESCRIPTION
**Pull request by ChristianMurphy**
updating dependencies with versions that are in range, makes `yarn audit` happy.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
This also allows `yarn` to install `iltorb` dependency on Node 12.

**Comment by jxnblk** [comment]
Looks like this might've broken emotion on the docs site – I'm looking into it https://mdxjs.com/

**Comment by ChristianMurphy** [comment]
Good catch @jxnblk.
Looks like one of the nested updates is messing with the loader or the theme.
I can revert, if need be.

**Comment by jxnblk** [comment]
I'm not entirely sure why it broke, but the Now deploy in #596 looks like it works?? I've also opened #597 to update some of the dependencies used in the docs site

**Pull request merged**
